In [2]:
# Generic library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
train_df=pd.read_csv("D:/Inceptez Technologies/Hackathon_15-Sep-2019/Hackathon/CreditScore/CreditScore_train.csv")
test_df=pd.read_csv("D:/Inceptez Technologies/Hackathon_15-Sep-2019/Hackathon/CreditScore/CreditScore_test.csv")

In [4]:
print("Train size : rows",train_df.shape[0]," and columns",train_df.shape[1])
print("Test size : rows",test_df.shape[0]," and columns",test_df.shape[1])

Train size : rows 80000  and columns 305
Test size : rows 20000  and columns 305


In [5]:
train_df.head(3)

x001   x002  x003   x004   x005  x006  x007  x008  x009  x010  ...  \
0  1084094  426.0  39.0  128.0  426.0     0     0     0     0     0  ...   
1  1287777  160.0   2.0   64.0  160.0     1     1     2     0     1  ...   
2  1483016  163.0  16.0  104.0  239.0     0     0     0     1     0  ...   

    x296    x297  x298  x299  x300  x301  x302  x303  x304    y  
0      0     NaN     0     0     0     0   NaN     0   NaN  807  
1  17318  0.8417     1     1     1     0   NaN     0   NaN  819  
2      0     NaN     0     0     0     0   NaN     0   NaN  803  

[3 rows x 305 columns]

In [6]:
train_df.columns

Index(['x001', 'x002', 'x003', 'x004', 'x005', 'x006', 'x007', 'x008', 'x009',
       'x010',
       ...
       'x296', 'x297', 'x298', 'x299', 'x300', 'x301', 'x302', 'x303', 'x304',
       'y'],
      dtype='object', length=305)

In [7]:
train_df.columns.difference(test_df.columns)

Index([], dtype='object')

In [8]:
train_df["source"] = "train"
test_df["source"] = "test"
df = pd.concat([train_df,test_df])

In [9]:
df.dtypes

x001        int64
x002      float64
x003      float64
x004      float64
x005      float64
x006        int64
x007        int64
x008        int64
x009        int64
x010        int64
x011        int64
x012        int64
x013        int64
x014        int64
x015        int64
x016        int64
x017        int64
x018        int64
x019        int64
x020        int64
x021        int64
x022        int64
x023        int64
x024        int64
x025        int64
x026        int64
x027        int64
x028        int64
x029        int64
x030        int64
           ...   
x277        int64
x278        int64
x279        int64
x280        int64
x281        int64
x282        int64
x283        int64
x284        int64
x285        int64
x286        int64
x287      float64
x288      float64
x289      float64
x290      float64
x291        int64
x292        int64
x293      float64
x294        int64
x295      float64
x296        int64
x297      float64
x298        int64
x299        int64
x300        int64
x301      

In [10]:
df.shape

(100000, 306)

In [11]:
df.describe().transpose()

count          mean            std    min           25%  \
x001  100000.0  1.218244e+06  272897.724977  517.0  974363.50000   
x002   78568.0  1.257117e+02     115.785117    0.0      32.00000   
x003   78568.0  2.554124e+01      49.028751    0.0       3.00000   
x004   78576.0  6.539321e+01      63.592317    0.0      19.00000   
x005   93890.0  1.782385e+02     124.520628    0.0      87.00000   
x006  100000.0  3.140400e-01       0.464135    0.0       0.00000   
x007  100000.0  6.940000e-01       1.379378    0.0       0.00000   
x008  100000.0  1.388220e+00       2.282805    0.0       0.00000   
x009  100000.0  1.192980e+00       2.031083    0.0       0.00000   
x010  100000.0  1.026990e+00       1.713823    0.0       0.00000   
x011  100000.0  1.843240e+00       2.711524    0.0       0.00000   
x012  100000.0  1.607940e+00       2.582390    0.0       0.00000   
x013  100000.0  1.576860e+00       2.609533    0.0       0.00000   
x014  100000.0  4.306830e+00       5.473131    0.0       0.00000   
x015  100000.0  1.294306e+01      11.957652    0.0       4.00000   
x016  100000.0  4.089260e+00       4.622082    0.0       1.00000   
x017  100000.0  8.853800e+00       9.254211    0.0       2.00000   
x018  100000.0  3.988200e+00       2.361058    0.0       2.00000   
x019  100000.0  2.147260e+00       1.748446    0.0       1.00000   
x020  100000.0  6.798700e+00       7.829639    0.0       1.00000   
x021  100000.0  2.283170e+00       3.161361    0.0       0.00000   
x022  100000.0  1.730500e+00       1.120072    0.0       1.00000   
x023  100000.0  1.085840e+00       1.011910    0.0       0.00000   
x024  100000.0  4.733060e+00       7.159681    0.0       1.00000   
x025  100000.0  3.185200e-01       0.465905    0.0       0.00000   
x026  100000.0  5.697900e-01       0.495108    0.0       0.00000   
x027  100000.0  7.515200e-01       0.432134    0.0       1.00000   
x028  100000.0  8.018500e-01       1.579586    0.0       0.00000   
x029  100000.0  1.476120e+00       2.036195    0.0       0.00000   
x030  100000.0  4.037540e+00       4.782564    0.0       1.00000   
...        ...           ...            ...    ...           ...   
x276  100000.0  2.565100e-01       0.939979    0.0       0.00000   
x277  100000.0  2.856100e-01       1.008686    0.0       0.00000   
x278  100000.0  3.488800e-01       1.131413    0.0       0.00000   
x279  100000.0  6.565756e+04  177914.758081    0.0      34.00000   
x280  100000.0  9.516506e+03   50262.873445    0.0       0.00000   
x281  100000.0  5.614105e+04  170525.864807    0.0       0.00000   
x282  100000.0  8.658500e-01       0.340815    0.0       1.00000   
x283  100000.0  8.738400e-01       0.332031    0.0       1.00000   
x284  100000.0  8.841400e-01       0.320059    0.0       1.00000   
x285  100000.0  1.391490e+00       2.682935    0.0       0.00000   
x286  100000.0  1.152600e-01       0.695126    0.0       0.00000   
x287   75179.0  3.239309e+00       3.090414    1.0       1.00000   
x288   50244.0  5.169799e+01      52.700032    0.0      14.00000   
x289   50244.0  2.544553e+01      34.674418    0.0       5.00000   
x290   50244.0  3.833166e+01      38.882567    0.0      11.66660   
x291  100000.0  1.461510e+04   37717.143370    0.0       0.00000   
x292  100000.0  5.839332e+04  164530.463427    0.0       0.00000   
x293   48867.0  8.125753e-01       0.321268    0.0       0.64060   
x294  100000.0  2.795508e+03   17515.777542    0.0       0.00000   
x295   13467.0  9.013038e-01       0.433850    0.0       0.65635   
x296  100000.0  1.181960e+04   32264.688940    0.0       0.00000   
x297   41888.0  7.940343e-01       0.288249    0.0       0.63690   
x298  100000.0  5.433200e-01       0.498122    0.0       0.00000   
x299  100000.0  5.580300e-01       0.496624    0.0       0.00000   
x300  100000.0  5.818300e-01       0.493261    0.0       0.00000   
x301  100000.0  1.062400e-01       0.308146    0.0       0.00000   
x302   26931.0  2.948758e+00       2.129430    1.0       1.00000 

In [12]:
df.duplicated().sum()


0

In [13]:
df.isna().sum()

x001          0
x002      21432
x003      21432
x004      21424
x005       6110
x006          0
x007          0
x008          0
x009          0
x010          0
x011          0
x012          0
x013          0
x014          0
x015          0
x016          0
x017          0
x018          0
x019          0
x020          0
x021          0
x022          0
x023          0
x024          0
x025          0
x026          0
x027          0
x028          0
x029          0
x030          0
          ...  
x277          0
x278          0
x279          0
x280          0
x281          0
x282          0
x283          0
x284          0
x285          0
x286          0
x287      24821
x288      49756
x289      49756
x290      49756
x291          0
x292          0
x293      51133
x294          0
x295      86533
x296          0
x297      58112
x298          0
x299          0
x300          0
x301          0
x302      73069
x303          0
x304      81875
y             0
source        0
Length: 306, dtype: int6

In [14]:
df.head(5)

x001   x002  x003   x004   x005  x006  x007  x008  x009  x010  ...  \
0  1084094  426.0  39.0  128.0  426.0     0     0     0     0     0  ...   
1  1287777  160.0   2.0   64.0  160.0     1     1     2     0     1  ...   
2  1483016  163.0  16.0  104.0  239.0     0     0     0     1     0  ...   
3   959054    NaN   NaN    NaN  102.0     0     0     0     0     0  ...   
4  1342113    3.0   2.0    2.0   62.0     0     2     2     0     0  ...   

     x297  x298  x299  x300  x301  x302  x303  x304    y  source  
0     NaN     0     0     0     0   NaN     0   NaN  807   train  
1  0.8417     1     1     1     0   NaN     0   NaN  819   train  
2     NaN     0     0     0     0   NaN     0   NaN  803   train  
3     NaN     1     1     1     0   NaN     0   NaN  530   train  
4  1.0180     1     1     1     0   NaN     0   NaN  485   train  

[5 rows x 306 columns]

In [15]:
df.tail(5)

x001   x002  x003   x004   x005  x006  x007  x008  x009  x010  ...  \
19995  1341378   51.0   3.0   18.0  120.0     0     1     3     0     1  ...   
19996  1290822  187.0  13.0  107.0  415.0     0     0     1     1     0  ...   
19997   795243   95.0  19.0   57.0   95.0     1     0     2     2     2  ...   
19998  1323781    NaN   NaN    NaN   40.0     0     0     0     0     5  ...   
19999  1341326    NaN   NaN    NaN   86.0     0     0     0     0     0  ...   

         x297  x298  x299  x300  x301  x302   x303    x304    y  source  
19995  0.9084     1     1     1     0   NaN      0     NaN  541    test  
19996  0.8273     1     1     1     0   NaN      0     NaN  831    test  
19997     NaN     1     1     1     0   5.0  30770  1.2299  543    test  
19998     NaN     1     1     1     0   NaN      0     NaN  488    test  
19999     NaN     0     0     0     1   NaN      0     NaN  491    test  

[5 rows x 306 columns]

In [16]:
# Identify discrete and continous columns
col_disc=[]
col_medium=[]
col_cont=[]
print("Attributes with their distinct count and their classification")
for i in df.columns:
    if df[i].nunique() <=10:
        print(i,"==",df[i].nunique(),"== disc")
        col_disc.append(i)
    elif (df[i].nunique() >10 and df[i].nunique() <100):
        col_medium.append(i)    
        print(i,"==",df[i].nunique(),"== medium")
    else:
        col_cont.append(i)
        print(i,"==",df[i].nunique(),"== cont")

Attributes with their distinct count and their classification
x001 == 100000 == cont
x002 == 666 == cont
x003 == 457 == cont
x004 == 492 == cont
x005 == 699 == cont
x006 == 2 == disc
x007 == 32 == medium
x008 == 44 == medium
x009 == 42 == medium
x010 == 30 == medium
x011 == 41 == medium
x012 == 38 == medium
x013 == 39 == medium
x014 == 60 == medium
x015 == 125 == cont
x016 == 58 == medium
x017 == 110 == cont
x018 == 17 == medium
x019 == 12 == medium
x020 == 95 == medium
x021 == 49 == medium
x022 == 7 == disc
x023 == 6 == disc
x024 == 106 == cont
x025 == 2 == disc
x026 == 2 == disc
x027 == 2 == disc
x028 == 30 == medium
x029 == 30 == medium
x030 == 69 == medium
x031 == 122 == cont
x032 == 27 == medium
x033 == 41 == medium
x034 == 59 == medium
x035 == 84 == medium
x036 == 41 == medium
x037 == 5 == disc
x038 == 12 == medium
x039 == 18 == medium
x040 == 28 == medium
x041 == 12056 == cont
x042 == 8728 == cont
x043 == 28977 == cont
x044 == 4384 == cont
x045 == 1262 == cont
x046 == 19 == medi

In [17]:
for i in col_disc:
    print(i ,"with distinct values \n",df[i].unique())
for i in col_medium:
    print(i ,"with distinct values \n",df[i].unique())

x006 with distinct values 
 [0 1]
x022 with distinct values 
 [3 0 1 2 4 5 6]
x023 with distinct values 
 [2 1 0 3 4 5]
x025 with distinct values 
 [1 0]
x026 with distinct values 
 [1 0]
x027 with distinct values 
 [1 0]
x037 with distinct values 
 [0 1 4 2 3]
x049 with distinct values 
 [0 1 3 5 2 4 6 7 9]
x050 with distinct values 
 [0 1 2 3 4 6 5 7]
x051 with distinct values 
 [0 1 2 3 6 4 5 7]
x052 with distinct values 
 [0 2 1 3 5 4 7 6]
x053 with distinct values 
 [0 4 1 2 3 7 5 6 8]
x060 with distinct values 
 [0 1]
x067 with distinct values 
 [0]
x068 with distinct values 
 [0 1 3 2 5 8 4]
x077 with distinct values 
 [0 1 2 3]
x078 with distinct values 
 [0 1 2 3 6 5]
x079 with distinct values 
 [ 0  1  2  3  4 20  5 11  6]
x082 with distinct values 
 [0 1]
x083 with distinct values 
 [0 1]
x084 with distinct values 
 [0 1]
x085 with distinct values 
 [0 1]
x086 with distinct values 
 [0 1]
x087 with distinct values 
 [0 1]
x088 with distinct values 
 [0 1]
x089 with distinct 

In [18]:
df.corr()

x001      x002      x003      x004      x005      x006      x007  \
x001  1.000000  0.097072  0.025511  0.087469  0.113784 -0.000547  0.010608   
x002  0.097072  1.000000  0.297062  0.831371  0.750919  0.120643 -0.129729   
x003  0.025511  0.297062  1.000000  0.705223  0.227947  0.240625 -0.259942   
x004  0.087469  0.831371  0.705223  1.000000  0.631568  0.229115 -0.271451   
x005  0.113784  0.750919  0.227947  0.631568  1.000000  0.122944 -0.056136   
x006 -0.000547  0.120643  0.240625  0.229115  0.122944  1.000000 -0.128729   
x007  0.010608 -0.129729 -0.259942 -0.271451 -0.056136 -0.128729  1.000000   
x008 -0.044504 -0.157916 -0.291211 -0.317127 -0.071533 -0.111982  0.816276   
x009 -0.030123 -0.081200 -0.206302 -0.212224 -0.023301 -0.006825  0.265456   
x010 -0.003545 -0.021819 -0.166482 -0.141670  0.026116  0.025752  0.177353   
x011  0.016469  0.043906 -0.147756 -0.073751  0.097613  0.055851  0.149122   
x012  0.026680  0.081502 -0.097560 -0.005380  0.124546  0.057546  0.105683   
x013  0.038326  0.143872 -0.065378  0.063455  0.194050  0.067632  0.085515   
x014  0.095711  0.525007  0.021962  0.386105  0.615036  0.120025  0.043744   
x015  0.047548  0.263891 -0.185542  0.055384  0.366518  0.075942  0.321664   
x016  0.030942  0.213365 -0.259247 -0.020783  0.194622 -0.114039  0.461959   
x017  0.045983  0.226280 -0.106323  0.079169  0.371721  0.155085  0.184903   
x018  0.080246  0.311074 -0.162806  0.107660  0.439052  0.159153  0.227665   
x019  0.082774  0.328338 -0.306516  0.030125  0.342145 -0.076371  0.354400   
x020  0.054282  0.327244 -0.126931  0.124374  0.439249  0.084989  0.292714   
x021  0.029643  0.225376 -0.212223 -0.002681  0.235643 -0.165828  0.479681   
x022  0.097580  0.379772 -0.072472  0.217595  0.494362  0.230647  0.216250   
x023  0.088210  0.341642 -0.208822  0.105042  0.376642 -0.137647  0.336373   
x024 -0.004985 -0.047485 -0.148690 -0.116558 -0.007196  0.010496  0.213128   
x025  0.106287  0.377780  0.008237  0.261186  0.455240  0.087319  0.006920   
x026  0.060710  0.082446 -0.161155 -0.038087  0.189101  0.063157  0.132056   
x027  0.075518  0.223222 -0.060263  0.123320  0.328381  0.387018  0.207551   
x028  0.093136  0.317674 -0.032325  0.191020  0.376122  0.067869  0.006919   
x029  0.055005  0.128936 -0.157491 -0.019995  0.216787  0.044409  0.129686   
x030  0.056276  0.320575 -0.118051  0.129996  0.422049  0.082614  0.258186   
...        ...       ...       ...       ...       ...       ...       ...   
x276 -0.046359 -0.088190 -0.043463 -0.086965 -0.078993  0.007875  0.069130   
x277 -0.045608 -0.086814 -0.046254 -0.087028 -0.078319  0.008388  0.066760   
x278 -0.042624 -0.086839 -0.049377 -0.087047 -0.079804  0.008965  0.057738   
x279  0.064553  0.232028 -0.080605  0.107065  0.226650  0.018353  0.045457   
x280  0.008337  0.048319  0.008794  0.042563  0.048235  0.020679 -0.002289   
x281  0.064893  0.226747 -0.086387  0.098595  0.222005  0.013053  0.048102   
x282  0.059686  0.023484 -0.145632 -0.051382  0.172545  0.128260  0.196721   
x283  0.056617  0.009369 -0.155693 -0.066022  0.157793  0.134254  0.190844   
x284  0.052680  0.003784 -0.149242 -0.066901  0.139261  0.144967  0.181814   
x285 -0.004256 -0.036206 -0.163689 -0.106613 -0.056368 -0.014827  0.222611   
x286 -0.026419 -0.057178 -0.016101 -0.040773 -0.065035  0.027102 -0.001961   
x287 -0.086583 -0.233109  0.031751 -0.157124 -0.286487  0.022682 -0.064154   
x288  0.010257  0.322543  0.327324  0.434729  0.155659  0.031372 -0.057043   
x289  0.014711  0.202176  0.643515  0.446792  0.127097  0.060495 -0.212806   
x290  0.015183  0.301601  0.512319  0.510682  0.155927  0.046928 -0.146270   
x291  0.016213  0.039694 -0.126204 -0.049349  0.044960 -0.012285  0.141716   
x292  0.060550  0.206732 -0.081050  0.089922  0.205639  0.021283  0.044235   
x293 -0.065975 -0.187345  0.016024 -0.149730 -0.242591 -0.033911  0.107047   
x294 -0.006394 -0.012817 -0.018867 -0.011747 -0.017443  0.013638  0.009940   
x295 -0.040756  0.015252  0.1090

In [19]:
df.corr()['y'].sort_values()

x041   -0.690840
x057   -0.636510
x058   -0.586811
x287   -0.562191
x242   -0.547844
x155   -0.542090
x302   -0.483852
x148   -0.483754
x253   -0.473823
x059   -0.415029
x065   -0.413885
x064   -0.411101
x162   -0.403556
x297   -0.374772
x293   -0.370417
x304   -0.368138
x063   -0.358450
x168   -0.348083
x173   -0.337363
x056   -0.336567
x278   -0.316596
x036   -0.312055
x172   -0.309105
x277   -0.308842
x099   -0.307428
x276   -0.307428
x062   -0.293974
x040   -0.291714
x073   -0.284965
x171   -0.283763
          ...   
x260    0.434920
x261    0.439065
x229    0.443279
x262    0.445821
x247    0.446191
x250    0.447270
x246    0.459512
x245    0.467735
x014    0.474342
x023    0.480639
x002    0.485744
x239    0.487305
x025    0.487376
x225    0.488159
x237    0.499302
x244    0.503321
x046    0.507595
x228    0.512067
x226    0.514055
x249    0.515316
x227    0.537190
x022    0.568884
x236    0.572875
x005    0.575970
x235    0.620394
y       1.000000
x067         NaN
x094         N

In [20]:
cor = df.corr()

In [21]:
#Correlation with output variable
cor_target = abs(cor["y"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.4]
relevant_features

x002    0.485744
x004    0.419683
x005    0.575970
x014    0.474342
x018    0.410462
x019    0.413284
x020    0.415688
x022    0.568884
x023    0.480639
x025    0.487376
x027    0.424206
x028    0.414760
x030    0.425470
x041    0.690840
x046    0.507595
x057    0.636510
x058    0.586811
x059    0.415029
x064    0.411101
x065    0.413885
x148    0.483754
x155    0.542090
x162    0.403556
x224    0.432531
x225    0.488159
x226    0.514055
x227    0.537190
x228    0.512067
x229    0.443279
x235    0.620394
x236    0.572875
x237    0.499302
x239    0.487305
x242    0.547844
x244    0.503321
x245    0.467735
x246    0.459512
x247    0.446191
x249    0.515316
x250    0.447270
x253    0.473823
x260    0.434920
x261    0.439065
x262    0.445821
x287    0.562191
x302    0.483852
y       1.000000
Name: y, dtype: float64

In [22]:
df.duplicated().sum()

0

In [23]:
df.isna().sum()

x001          0
x002      21432
x003      21432
x004      21424
x005       6110
x006          0
x007          0
x008          0
x009          0
x010          0
x011          0
x012          0
x013          0
x014          0
x015          0
x016          0
x017          0
x018          0
x019          0
x020          0
x021          0
x022          0
x023          0
x024          0
x025          0
x026          0
x027          0
x028          0
x029          0
x030          0
          ...  
x277          0
x278          0
x279          0
x280          0
x281          0
x282          0
x283          0
x284          0
x285          0
x286          0
x287      24821
x288      49756
x289      49756
x290      49756
x291          0
x292          0
x293      51133
x294          0
x295      86533
x296          0
x297      58112
x298          0
x299          0
x300          0
x301          0
x302      73069
x303          0
x304      81875
y             0
source        0
Length: 306, dtype: int6

In [24]:
df=df.replace(np.nan,0)

In [25]:
credit_df=df.drop(columns=["x302", "x304", "x297","x002","x003","x004","x005","x287","x288","x289","x290","x293","x295"])
credit_df.head(10)

x001  x006  x007  x008  x009  x010  x011  x012  x013  x014  ...    x292  \
0  1084094     0     0     0     0     0     2     4     4     9  ...  346762   
1  1287777     1     1     2     0     1     3     3     7     5  ...  124634   
2  1483016     0     0     0     1     0     1     0     0     6  ...       0   
3   959054     0     0     0     0     0     0     2     2     0  ...       0   
4  1342113     0     2     2     0     0     1     2     0     0  ...   17413   
5   807817     1     0     0     0     0     0     0     2     9  ...       0   
6   906658     0     0     0     0     0     2     1     1    15  ...  696762   
7  1202685     1     0     0     5     1     0     1     0    11  ...    8883   
8  1547270     0     1     1     0     1     3     3     4     0  ...       0   
9  1163310     1     0     0     1     3     2     0     0     0  ...       0   

   x294   x296  x298  x299  x300  x301  x303    y  source  
0     0      0     0     0     0     0     0  807   train  
1     0  17318     1     1     1     0     0  819   train  
2     0      0     0     0     0     0     0  803   train  
3     0      0     1     1     1     0     0  530   train  
4     0  17413     1     1     1     0     0  485   train  
5     0      0     0     0     0     0     0  665   train  
6     0      0     0     0     0     0     0  751   train  
7     0   8883     1     1     1     0     0  751   train  
8     0      0     1     1     1     0     0  642   train  
9     0      0     1     1     1     0     0  473   train  

[10 rows x 293 columns]

In [26]:
train_final = credit_df[credit_df.source=="train"]
test_final = credit_df[credit_df.source=="test"]

In [27]:
train_final.drop(columns="source",inplace=True)
test_final.drop(columns="source",inplace=True)


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [28]:
#split train and data
train_X = train_final.drop(columns=["y"])
train_Y = train_final["y"]
test_X = test_final.drop(columns=["y"])
test_Y = test_final["y"]

In [29]:
train_final[train_final["y"]==0]

Empty DataFrame
Columns: [x001, x006, x007, x008, x009, x010, x011, x012, x013, x014, x015, x016, x017, x018, x019, x020, x021, x022, x023, x024, x025, x026, x027, x028, x029, x030, x031, x032, x033, x034, x035, x036, x037, x038, x039, x040, x041, x042, x043, x044, x045, x046, x047, x048, x049, x050, x051, x052, x053, x054, x055, x056, x057, x058, x059, x060, x061, x062, x063, x064, x065, x066, x067, x068, x069, x070, x071, x072, x073, x074, x075, x076, x077, x078, x079, x080, x081, x082, x083, x084, x085, x086, x087, x088, x089, x090, x091, x092, x093, x094, x095, x096, x097, x098, x099, x100, x101, x102, x103, x104, ...]
Index: []

[0 rows x 292 columns]

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import cross_val_score

model_metrics={}
def calc_metrics_and_predict(model,model_label,train_X,test_X,train_Y,test_Y,test_final, scaler,cv):
    if scaler is not None:
        # Scaling
        print("Scaling applied")
        train_X = scaler.fit_transform(train_X)
        test_X = scaler.transform(test_X)
    print("fit data")    
    model.fit(train_X, train_Y)
    print("predict data")
    yhat_train = model.predict(train_X)
    rmse=np.sqrt(mean_squared_error(train_Y, yhat_train))
    mae=mean_absolute_error(train_Y,yhat_train)
    #mape=np.mean(np.abs((train_Y - yhat_train) / train_Y)) * 100
    mape=mae * 100
    if cv==True:
        print("Cross-Validation score")
        scores = cross_val_score(model, train_X, train_Y, cv = 10,scoring='neg_mean_squared_error') 
        avg_cross_val_score = np.mean(np.sqrt(np.abs(scores)))
    else:
        avg_cross_val_score=None
    #avg_cross_val_score=0
    model_metrics[model_label]=[rmse,mae,mape,avg_cross_val_score]
    # Predict test data and add to test_fnal dataframe
    test_final[model_label] =  model.predict(test_X)
    return model_metrics

In [31]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold
rmf = RandomForestRegressor(n_jobs = -1)

model_metrics=calc_metrics_and_predict(rmf,'Random Forest',train_X,test_X,train_Y,test_Y,test_final,None, True)
model_metrics

fit data


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


predict data
Cross-Validation score


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


{'Random Forest': [13.154050502601851,
  8.69331375,
  869.331375,
  30.760132138147195]}

In [32]:
# Linear regression
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
        
model_metrics=calc_metrics_and_predict(linear_model,'linear_reg',train_X,test_X,train_Y,test_Y,test_final,None,True)
model_metrics

fit data
predict data
Cross-Validation score


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


{'Random Forest': [13.154050502601851,
  8.69331375,
  869.331375,
  30.760132138147195],
 'linear_reg': [48.7021181655362,
  36.73014255120028,
  3673.014255120028,
  49.285610812129036]}

In [33]:
# linear model with cross-validation
from sklearn.model_selection import cross_val_score
a = cross_val_score(linear_model, train_X, train_Y, cv=10, scoring='neg_mean_squared_error')
np.mean(np.sqrt(np.abs(a)))

49.285610812129036

In [34]:
# Regularization technique
from sklearn.linear_model import Ridge, Lasso 

# List to maintain the different cross-validation scores 
cross_val_scores_ridge = [] 
  
# List to maintain the different values of alpha 
alpha = [] 
  
# Loop to compute the different values of cross-validation scores 
for i in range(1, 9): 
    ridgeModel = Ridge(alpha = i * 0.25) 
    ridgeModel.fit(train_X, train_Y) 
    scores = cross_val_score(ridgeModel, train_X, train_Y, cv = 10,scoring='neg_mean_squared_error') 
    avg_cross_val_score = np.mean(np.sqrt(np.abs(scores)))
    cross_val_scores_ridge.append(avg_cross_val_score) 
    alpha.append(i * 0.25) 
  
# Loop to print the different values of cross-validation scores 
for i in range(0, len(alpha)): 
    print(str(alpha[i])+' : '+str(cross_val_scores_ridge[i])) 

C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.24364e-17): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=4.9603e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.25759e-17): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.18017e-17): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.185

0.25 : 49.2856305075892
0.5 : 49.28564093915655
0.75 : 49.28565651850393
1.0 : 49.28567560750814
1.25 : 49.28569734241744
1.5 : 49.285721206872076
1.75 : 49.28574685965331
2.0 : 49.2857740566406


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=9.52191e-17): result may not be accurate.
  overwrite_a=True).T


In [35]:
#Building ridge model
ridgeModel = Ridge(alpha = 1 * 0.25) 
model_metrics=calc_metrics_and_predict(ridgeModel,'regularization',train_X,test_X,train_Y,test_Y,test_final,None,True)
model_metrics

fit data
predict data
Cross-Validation score


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.24364e-17): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=4.9603e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.25759e-17): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.18017e-17): result may not be accurate.
  overwrite_a=True).T
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.185

{'Random Forest': [13.154050502601851,
  8.69331375,
  869.331375,
  30.760132138147195],
 'linear_reg': [48.7021181655362,
  36.73014255120028,
  3673.014255120028,
  49.285610812129036],
 'regularization': [48.70212370461082,
  36.73007802203817,
  3673.007802203817,
  49.2856305075892]}

In [36]:
# Bernoulli
from sklearn.naive_bayes import BernoulliNB

BL=BernoulliNB()

model_metrics=calc_metrics_and_predict(BL,'NB_BernoulliNB',train_X,test_X,train_Y,test_Y,test_final,None,True)
model_metrics

fit data
predict data
Cross-Validation score


C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Venkat\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


{'Random Forest': [13.154050502601851,
  8.69331375,
  869.331375,
  30.760132138147195],
 'linear_reg': [48.7021181655362,
  36.73014255120028,
  3673.014255120028,
  49.285610812129036],
 'regularization': [48.70212370461082,
  36.73007802203817,
  3673.007802203817,
  49.2856305075892],
 'NB_BernoulliNB': [78.63961994440207,
  55.174675,
  5517.4675,
  78.36482467247076]}

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rfm=RandomForestRegressor(random_state = 0, criterion='mse',n_jobs = -1, 
        n_estimators = 100, max_depth = None,min_samples_leaf=1,min_samples_split=2)

model_metrics=calc_metrics_and_predict(rfm,'Random_forest',train_X,test_X,train_Y,test_Y,test_final,None,True)
model_metrics

fit data
predict data
Cross-Validation score


In [ ]:
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor(criterion='mse', max_depth=100, max_features='log2', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, min_samples_leaf=5, min_samples_split=8, min_weight_fraction_leaf=0.0, presort=False, random_state=None, splitter='best')


model_metrics=calc_metrics_and_predict(clf,'Decision_Tree',train_X,test_X,train_Y,test_Y,test_final,None,True)
model_metrics